### ISSUE TITLE
cz: zacit pouzivat pocet aktualne nakazenych

### ISSUE THREAD

**Issue by stepanex** [stepanex/CoronavirusMap#43]

**Comment by stepanex** [comment]
musim pockat az budou aktivni cisla i u regionu

**Comment by kukosek** [comment]
Nemyslím si že toto je dobrý nápad. Pak když se bude někdo dívat zpětně tak uvidí všude nulu a nebude mět ponětí jaké kraje byli nejvíc zamořené.

**Comment by stepanex** [comment]
pravda, díky
